### PR TITLE
Add a Dockerfile to build the application as a container

### PR DESCRIPTION
**Pull request by OrangeCrush**
Wanted to share the Dockerfile I have been using with the group.  Tested and working well.  Building the container takes about 20 hours (The database is rebuilt each time)

Open to any feedback / suggestions.  If we can get the build time down (commit a prebuilt DB into master?) we would be able to set up an automated build pipeline to dockerhub so people could pull down and use the app without the need to build it.

### CODE REVIEW

**Comment by phalt** [comment]
twenty hours? Is that a typo?

**Comment by phalt** [comment]
Can we add an option to populate minimal test data. 20 hour build times is not practical. The scripts can be run in 20-30 minutes so I don't understand why a build would take that long.

**Comment by OrangeCrush** [comment]
Anytime I build the complete database per the README it takes close to 20 hours for the following command to complete-

printf "execfile('data/v2/build.py')" | python manage.py shell --settings=config.local

I will see if I can decouple the database from the container into a "data" container so that the app can be rebuilt separately from the database.

Am I do something wrong here?  I do not know Django very well... Let me know.

**Comment by zaneadix** [comment]
Woof. 20 hours sounds crazy. Maybe this has something to do with local settings? I'm honestly rarely working against the lite db. Do you have a full postgres instance running? Have you tried it without running local settings? Regardless that's a problem. It's usually taking about 20 minutes for me right now.

**Comment by OrangeCrush** [comment]
OK.  So I have had a change to get back to this.. I have added 2 new commits to the PR.

I did take a look at the postgres setup and it did reduce the build time by quite a bit for all of the "v2" data.  It now builds in roughly 90 minutes on my desktop.. Thanks for the suggestion

```
Successfully built 3fbd129a5aeb

real    92m21.323s
user    0m0.302s
sys     0m0.112s
```

Unfortunately this is still too long to set up an automated build on dockerhub for right now. (see the issue I have open [here](https://github.com/docker/hub-feedback/issues/512) )

You can check out the container image I have pushed into dockerhub [here](https://hub.docker.com/r/orangecrush/pokeapi/).

What do you guys think about merging this?  Let me know your thoughts.  
Thanks

**Comment by phalt** [comment]
Hehe I think this is a problem we're not going to be able to avoid easily. It's a *lot* of data after all. Perhaps we can make the docker file just build the framework then we can manually run the data afterwards? Or perhaps we can just load some test data (like 1 or 2 pokemon and some sample data for the rest)?

**Comment by zaneadix** [comment]
It'd be great to have some decently fleshed out test data. Work done in #75 which has already been merged in has taken care of a lot of what makes this a problem by breaking out the data building into chunks so you don't have to build the whole thing at once.

**Comment by OrangeCrush** [comment]
I'm curious if there is any interest in merging this in as is at this point?  We could have a separate container with test data applied if someone has use cases.

I think there are a lot of benefits of using the full database in a docker container with this project... 

* *Super* useful for the end user to be able to run the latest API code locally with one command.
* For the heads down pokeapi dev's it's useful to be able to quickly test if the database still builds from scratch
* Drastically improve any kind of deployment and minimize downtime.

**Comment by phalt** [comment]
@OrangeCrush Happy to merge it but I have two questions:

1) How dramatically will this affect the current production project? I am not 100% familiar with docker and I want to avoid downtime getting this up and running.
2) Will this reduce barrier to entry for people who don't have docker. I.e. - can I still dev normally without it?

**Comment by OrangeCrush** [comment]
@phalt -

1) The changes I made give people the option to build the app as a "Docker Container".  Nothing needs to change for the production project, unless you are interested in using docker to deploy it.  Using docker would be completely optional.  Most projects are not using Docker in production.

2) Again, no one is required to build the application as a container, so this would not have any impact on those who may not have access to use docker.

Speaking of "barrier to entry" though, IMO this drastically reduces the barrier for other folks who would like to consume the API for their own projects.  Being able to build (or download) the entire running application to a desktop environment make's it much easier to do development.

Ultimately what docker allows you to do is programmatically build (and run) an application in a brand-new, fresh environment.  Think of the container as a service running on your machine.

I can definitely take some time to update the documentation if you think that is needed before merge.

I'm curious if you are developing on Linux yourself?

**Comment by nimaje** [comment]
a thought:
How about a repo for configs which aren't needed, but could be useful, like this Dockerfile,
because there are more programms which do similar tasks and why should we only support some of them if we add this others could be requested with  reference to this issue.
A repo for such configs would sepperate optional configs from the main project. A weaker separation would be a folder `optional_configs` (or similar).
As far as I know docker only works on Linux and I don't know how it would use `apt` on something like arch or gentoo.

**Comment by OrangeCrush** [comment]
@nimaje -
Docker can be run on any 64 bit operating system (including Mac and Windows).  I personally find it easiest to use Linux (for everything =] ) which is why I was asking about it.

Since the Dockerfile I wrote uses Ubuntu as it's parent container, the "apt" binary is already packaged inside of the container's chroot.  Although I have not specifically tested this container on gentoo or arch linux.. the entire crux of Docker is to solve this problem (build once, deploy anywhere), so I am more than confident that it will run anywhere without issues.  I have personally tested the container on Centos v6 & v7, Ubuntu v14 & v15, and Atomic v1.6.

Finally, I don't think it makes sense to keep the Dockerfile in a separate git repository.  Building the app in a container is dependent on the source code, so in my opinion they should live together.

**Comment by OrangeCrush** [comment]
I think there may have been some confusion with something I did not realize was in this PR.  There are no changes to the default "config/local.py" file.

I amended my PR to appropriately reflect this... I hope this clears things up as well

**Comment by phalt** [comment]
@OrangeCrush perfect answers :) I dev on mac os x with docker, just not for this project as it was before docker existed :D

**Comment by nimaje** [comment]
I suggested a repo as *seperation*. I know that Docker *will need* the source if you use it,
but this project *doesn't need* the Dockerfile ( it could be useful for some).
As a weaker seperation I suggested a subdir which indicates everything in it is optinal.
(Just to explain my thought)

**Pull request merged**
