### PR TITLE
Initial Django REST framework progress

### PR DESCRIPTION
**Pull request by phalt**
Currently a WIP

### CODE REVIEW

**Comment by vamsivarikuti** [comment]
Hi phalt, can you merge this pull request into master. I'm free today. I'll checkout the "csv to database" task #9. The database should be accessed as an api through django-rest-framework right?

**Comment by phalt** [comment]
@vamsivarikuti this is no where near being completed :P

**Comment by phalt** [comment]
Updated to reflect new model changes. Not yet complete.

**Comment by zaneadix** [comment]
Hey @phalt has this actually been working for you so far? I've been tinkering with this and feel like I have things wired up right for Abilities and no matter what I do when I visit http://localhost:8000/api/v2/ability/ I get a 500 page.

**Comment by phalt** [comment]
@zaneadix sorry no. As I keep saying - I'm building APIs full time at work and development on this has all but stopped :cry: I committed this half done, so it doesn't surprise me there are 500's. Turn on DEBUG=True and that'll point in the right direction!

**Comment by zaneadix** [comment]
Thanks for getting back. I found out it was actually just a few missing commas in the REST_FRAMEWORK settings. I've got Abilities serving now. Working on more.

**Pull request merged**
