### PR TITLE
V2 images

### PR DESCRIPTION
**Pull request by zaneadix**
check it and critique.

I've added a sprites directory to data/v2 which is organized  for use in the build script which no dynamically builds out pokemon, pokemon form and item sprite models. The models are not complex. They just reference a foreign key and have a single field called 'sprites' that contains a stringified list of image paths.

I've updated the tests and documentation.

pokemon sprites field
```
sprites: {
		"back_female": "http://localhost:8000/media/sprites/pokemon/back/female/12.png",
		"back_shiny_female": "http://localhost:8000/media/sprites/pokemon/back/shiny/female/12.png",
		"back_default": "http://localhost:8000/media/sprites/pokemon/back/12.png",
		"front_female": "http://localhost:8000/media/sprites/pokemon/female/12.png",
		"front_shiny_female": "http://localhost:8000/media/sprites/pokemon/shiny/female/12.png",
		"back_shiny": "http://localhost:8000/media/sprites/pokemon/back/shiny/12.png",
		"front_default": "http://localhost:8000/media/sprites/pokemon/12.png",
		"front_shiny": "http://localhost:8000/media/sprites/pokemon/shiny/12.png"
	}
```

pokemon form sprites field
```
sprites: {
		"back_default": "http://localhost:8000/media/sprites/pokemon/back/12.png",
		"back_shiny": "http://localhost:8000/media/sprites/pokemon/back/shiny/12.png",
		"front_default": "http://localhost:8000/media/sprites/pokemon/12.png",
		"front_shiny": "http://localhost:8000/media/sprites/pokemon/shiny/12.png"
	}
```

item sprites field
```
sprites: {
		"default": "http://localhost:8000/media/sprites/items/great-ball.png",
	}
```

### CODE REVIEW

**Comment by zaneadix** [comment]
Woof. I'm sorry about the number of files changed. It's the sprites.

**Comment by phalt** [comment]
Haha lol

**Comment by phalt** [comment]
@zaneadix If we merge this in and get it up on beta.pokeapi.co is that the best way to test this?

**Comment by phalt** [comment]
@zaneadix can't see any software tests in this PR?

**Comment by zaneadix** [comment]
@phalt yeah it looks like the tests diff is getting truncated by the sprite hell. I could always remove the sprites from the commit and just pass the directory to you. They would just need to be stored in '/media/sprites'. I'm fairly confident things will work well if the changes we're pushed up to beta.pokeapi.co

**Comment by phalt** [comment]
@zaneadix commit just enough to make the tests pass and so we can review them, and make a separate PR with all the images. Or do it the other way around: commit the images first, merge it, then we can review the code after.

**Comment by zaneadix** [comment]
@phalt I removed the images from the commit. Once we're good on the code changes I can add them back in before we merge.

**Comment by zaneadix** [comment]
@phalt Have you had a chance to check out the source since I removed the images? Any changes you would recommend?

**Comment by phalt** [comment]
@zaneadix yeah this is all good, but I can't merge as there is a conflict?

**Pull request merged**
