### PR TITLE
Improve db build

### PR DESCRIPTION
**Pull request by nimaje**
The db build module was a huge mess with only two functions and the main code on module-level. I have changed that. Now you can import it and only call the functions you want to execute.
Furthermore I have made some little changes to make it python3 compatible.
The db build has needed 22h on my computer (local settings).  All test passed, but I don't know if there are tests about the completeness of the db.

### CODE REVIEW

**Comment by zaneadix** [comment]
Thanks @nimaje. Gave this a quick glance and it looks awesome. This project is my first time coding in python so i've probably done a bunch of questionable stuff. I'll pull this down and check it out soon. Would you also be able to update the readme? Is there still a method that would allow us to run all methods?

**Comment by nimaje** [comment]
yes. The methode in the readme should work, but I don't know django (`__name__` has to be `__main__` in the module that it run) . To run all methods there is `build_all`.

**Comment by cstrachan88** [comment]
I noticed there was a duplicate call to PokemonGameIndex (at line 2048) so I edited your updated build .py for v2, @nimaje. I haven't used github in a while so I don't know if there's anything else I need to do besides fork and edit the file.

**Comment by nimaje** [comment]
thanks @cstrachan88. such things were meant with mess (I think this was the only dublicate). And the use of `enumerate` to skip the header of the csv (not changed yet).

**Comment by zaneadix** [comment]
I've tested everything out and this seems to be good to go. I've made a small pull request with some documentation changes. Can you merge that in and then I'll merge this into the main branch. Thanks :)

**Comment by nimaje** [comment]
I have made some changes because of the starimports in the examples and the list with the build functions was under the v1 section I have move it under the v2 section

**Comment by zaneadix** [comment]
whoops. Thats what I get from trying to sneak edit this stuff at work. Thanks @nimaje nimaje

**Pull request merged**
