### PR TITLE
Fix #94

### LINKED ISSUE #94: Resource Lists - Mismatch between expected and actual JSON
The [docs for resource lists](http://pokeapi.co/docsv2/#resource-lists) say that 'calling any api endpoint without a resource id or name will return a paginated list of available resources for that api' with a shape like:

```json
{
    "count": 365,
    "next": "http://pokeapi.co/api/v2/evolution-chain/?limit=20&offset=20",
    "previous": null,
    "results": [{
        "url": "http://pokeapi.co/api/v2/evolution-chain/1/"
    }]
}
```

When I hit a resource list endpoint, though, the results from the actual endpoints are different than expected. They currently seem to:

- return only the contents of what would be in the `results` object (i.e. an array of `{ url, ?name }` objects)
- ignore query parameters, so `limit` and `offset` seem to have no effect on what gets returned

For example, using `httpie`:

```bash
http http://pokeapi/api/v2/pokemon/
```
I get the following output:

```
HTTP/1.1 200 OK
Allow: GET, HEAD, OPTIONS
Connection: keep-alive
Content-Type: application/json
Date: Mon, 08 Feb 2016 23:46:36 GMT
Server: nginx/1.1.19
Transfer-Encoding: chunked
Vary: Cookie
X-Frame-Options: SAMEORIGIN

[
    {
        "name": "bulbasaur",
        "url": "http://pokeapi.co/api/v2/pokemon/1/"
    },
    {
        "name": "ivysaur",
        "url": "http://pokeapi.co/api/v2/pokemon/2/"
    },
    {
        "name": "venusaur",
        "url": "http://pokeapi.co/api/v2/pokemon/3/"
    },

    [ . . . ]

    {
        "name": "latias-mega",
        "url": "http://pokeapi.co/api/v2/pokemon/10062/"
    },
    {
        "name": "latios-mega",
        "url": "http://pokeapi.co/api/v2/pokemon/10063/"
    }
]
```

I've curl'd, httpie'd, postman'd, and (far)fetch'd on a handful of different machines in different areas, so I don't *think* it's a problem on my end, but it's totally possible that I'm screwing up something completely simple and obvious :sweat_smile:

---

**tl;dr -- Are the docs for resource list endpoints outdated? Or are the docs correct and the API results are wrong? Or am I screwing up somewhere?**

Thanks! :grinning:

### PR DESCRIPTION
**Pull request by bdchauvette**
So it's ugly, but it works. I wasn't sure how to write tests for this, but I human tested it on both DRF 3.1 and DRF 3.3, and both gave me the following JSON for the `/api/v2/language/` endpoint:

```json
{
  "count": 11,
  "next": null,
  "previous": null,
  "results": [
    {
      "name": "ja",
      "url": "http://localhost:8000/api/v2/language/1/"
    },
    {
      "name": "roomaji",
      "url": "http://localhost:8000/api/v2/language/2/"
    },
    {
      "name": "ko",
      "url": "http://localhost:8000/api/v2/language/3/"
    },
    {
      "name": "zh",
      "url": "http://localhost:8000/api/v2/language/4/"
    },
    {
      "name": "fr",
      "url": "http://localhost:8000/api/v2/language/5/"
    },
    {
      "name": "de",
      "url": "http://localhost:8000/api/v2/language/6/"
    },
    {
      "name": "es",
      "url": "http://localhost:8000/api/v2/language/7/"
    },
    {
      "name": "it",
      "url": "http://localhost:8000/api/v2/language/8/"
    },
    {
      "name": "en",
      "url": "http://localhost:8000/api/v2/language/9/"
    },
    {
      "name": "cs",
      "url": "http://localhost:8000/api/v2/language/10/"
    },
    {
      "name": "ja-kanji",
      "url": "http://localhost:8000/api/v2/language/11/"
    }
  ]
}
```

### CODE REVIEW

**Comment by phalt** [comment]
@bdchauvette I don't think we should support diverging versions of DRF. We should just update DRF to a particular version and then use the settings for that one. Let's go for the most recent version if we can, nothing is holding us back.

**Comment by bdchauvette** [comment]
@phalt, I totally agree. This PR is super smelly.

The current code should actually run fine on any DRF version >=3.1, so if you can upgrade the server easily, I think that'd be a much cleaner / saner solution.

**Comment by phalt** [comment]
@bdchauvette yep, easy to bump up the version. Let's go ahead and support the newest one and not do this backwards compatible fix :)

**Comment by zaneadix** [comment]
@bdchauvette @phalt Where are we on this one? Should we just close this PR and make sure DRF gets upgraded with the next deployment? Regardless, thanks for digging into this @bdchauvette

**Comment by bdchauvette** [comment]
@zaneadix @phalt Sorry for the delay :sweat:

I've updated the PR to be a simple version bump for DRF.

DRF 3.1 is [when the new pagination API was introduced](http://www.django-rest-framework.org/topics/3.1-announcement/), so hopefully setting that as the minimum should be fine for the server?

**Comment by phalt** [comment]
@bdchauvette absolutely no problem, we've all got day jobs :)

Did you run the tests? (we should really set up circleci)

**Comment by bdchauvette** [comment]
I hadn't run the tests before (oops!) but I just ran them now.

### Update dependencies
```
$ make install
pip install -r requirements.txt --upgrade
Requirement already up-to-date: Django==1.7.1 in ./venv/lib/python2.7/site-packages (from -r requirements.txt (line 1))
Requirement already up-to-date: Pillow==2.6.1 in ./venv/lib/python2.7/site-packages (from -r requirements.txt (line 2))
Requirement already up-to-date: South==1.0 in ./venv/lib/python2.7/site-packages (from -r requirements.txt (line 3))
Requirement already up-to-date: Unipath==1.0 in ./venv/lib/python2.7/site-packages (from -r requirements.txt (line 4))
Requirement already up-to-date: coverage==3.6 in ./venv/lib/python2.7/site-packages (from -r requirements.txt (line 5))
Requirement already up-to-date: django-appconf==0.6 in ./venv/lib/python2.7/site-packages (from -r requirements.txt (line 6))
Requirement already up-to-date: django-cors-headers==1.0.0 in ./venv/lib/python2.7/site-packages (from -r requirements.txt (line 7))
Requirement already up-to-date: django-discover-runner==0.4 in ./venv/lib/python2.7/site-packages (from -r requirements.txt (line 8))
Requirement already up-to-date: django-imagekit==3.2.4 in ./venv/lib/python2.7/site-packages (from -r requirements.txt (line 9))
Requirement already up-to-date: django-tastypie==0.12.1 in ./venv/lib/python2.7/site-packages (from -r requirements.txt (line 10))
Requirement already up-to-date: django-markdown-deux==1.0.5 in ./venv/lib/python2.7/site-packages (from -r requirements.txt (line 11))
Requirement already up-to-date: djangorestframework>=3.1.0 in ./venv/lib/python2.7/site-packages (from -r requirements.txt (line 12))
Requirement already up-to-date: gunicorn==0.17.0 in ./venv/lib/python2.7/site-packages (from -r requirements.txt (line 13))
Requirement already up-to-date: markdown2==2.3.0 in ./venv/lib/python2.7/site-packages (from -r requirements.txt (line 14))
Requirement already up-to-date: mimeparse==0.1.3 in ./venv/lib/python2.7/site-packages (from -r requirements.txt (line 15))
Requirement already up-to-date: pilkit==1.1.12 in ./venv/lib/python2.7/site-packages (from -r requirements.txt (line 16))
Requirement already up-to-date: psycopg2==2.5.4 in ./venv/lib/python2.7/site-packages (from -r requirements.txt (line 17))
Requirement already up-to-date: python-dateutil==2.3 in ./venv/lib/python2.7/site-packages (from -r requirements.txt (line 18))
Requirement already up-to-date: python-mimeparse==0.1.4 in ./venv/lib/python2.7/site-packages (from -r requirements.txt (line 19))
Requirement already up-to-date: simplejson==3.6.5 in ./venv/lib/python2.7/site-packages (from -r requirements.txt (line 20))
Requirement already up-to-date: six==1.8.0 in ./venv/lib/python2.7/site-packages (from -r requirements.txt (line 21))
Requirement already up-to-date: wsgiref==0.1.2 in /usr/lib/python2.7 (from -r requirements.txt (line 22))
```

### Make sure we're running DRF >=3.1.0
```sh
$ pip show djangorestframework
---
Metadata-Version: 2.0
Name: djangorestframework
Version: 3.3.2
Summary: Web APIs for Django, made easy.
Home-page: http://www.django-rest-framework.org
Author: Tom Christie
Author-email: tom@tomchristie.com
License: BSD
Location: $POKEAPI_DIR/venv/lib/python2.7/site-packages
Requires:
```
### Run Tests
```
$ make test
python manage.py test --settings=config.local
Creating test database for alias 'default'...
$POKEAPI_DIR/venv/lib/python2.7/site-packages/tastypie/resources.py:2210: RemovedInDjango18Warning: commit_on_success is deprecated in favor of atomic.
  @transaction.commit_on_success()

2016-03-03 - 1
.2016-03-03 - 1
.2016-03-03 - 1
.2016-03-03 - 1
.2016-03-03 - 1
.2016-03-03 - 1
.2016-03-03 - 1
.2016-03-03 - 1
.2016-03-03 - 1
.2016-03-03 - 1
.2016-03-03 - 1
.2016-03-03 - 1
.2016-03-03 - 1
.2016-03-03 - 1
.2016-03-03 - 1
.2016-03-03 - 1
.2016-03-03 - 1
.2016-03-03 - 1
.2016-03-03 - 1
.2016-03-03 - 1
.2016-03-03 - 1
.2016-03-03 - 1
.2016-03-03 - 1
.2016-03-03 - 1
.2016-03-03 - 1
.2016-03-03 - 1
.2016-03-03 - 1
.2016-03-03 - 1
.2016-03-03 - 1
.2016-03-03 - 1
.2016-03-03 - 1
.2016-03-03 - 1
.2016-03-03 - 1
.2016-03-03 - 1
.2016-03-03 - 1
.2016-03-03 - 1
.2016-03-03 - 1
.2016-03-03 - 1
.2016-03-03 - 1
.2016-03-03 - 1
.2016-03-03 - 1
.2016-03-03 - 1
.2016-03-03 - 1
.2016-03-03 - 1
.2016-03-03 - 1
.2016-03-03 - 1
.2016-03-03 - 1
..
----------------------------------------------------------------------
Ran 48 tests in 2.008s

OK
Destroying test database for alias 'default'...
```

I ran the tests using Python 2.7, because pip complains about `wsgiref` when running `make install` on Python 3.5.1.

**Comment by phalt** [comment]
This is perfect. thanks @bdchauvette !

**Comment by bdchauvette** [comment]
Cheers :D

**Pull request merged**
