### PR TITLE
Add mascalade-pokeapi wrapper to v1 docs

### PR DESCRIPTION
**Pull request by sh0hei**
Here's the project: https://github.com/sh0hei/mascalade-pokeapi

### CODE REVIEW

**Comment by phalt** [comment]
Thank you! You will need to fetch the master branch and merge it into your project as your branch is out of date. I am happy with the changes so I can merge it straight away afterwards :)

**Comment by sh0hei** [comment]
Sorry, merged master branch :)

**Comment by phalt** [comment]
:tada: thank you @sh0hei ! Next time I deploy this will go live :)

**Comment by sh0hei** [comment]
anytime :+1:

**Pull request merged**
