### PR TITLE
Complete models and improved build script

### PR DESCRIPTION
**Pull request by zaneadix**
-Added models for Pokemon, Moves, and all other remaining models.

-Added new models to build script

-Build script will now clean and reset auto-incrementers for each table
in pokeapi_co_db

-Build script now runs against both postgres and sqlite (dev)

-Added all models to admin site registry

-Added instructions for building out db in README

### CODE REVIEW

**Comment by zaneadix** [comment]
This would need pull request #39 to work. Hopefully this is much easier to look over.

**Comment by zaneadix** [comment]
@phalt have you had a chance to look over this at all?

**Comment by zaneadix** [comment]
@phalt is anybody out there?

**Comment by phalt** [comment]
@zaneadix sorry man these got lost in my notifications. I've been a bit busy. I can merge this now but I can't deploy it until I've tested it. Do you need it merged for more development?

**Comment by zaneadix** [comment]
@phalt Its cool. I've been wrapped up in things as well. It would be ideal to merge for further development. The main thing that's held me back from digging into other things was hoping this would get merged so I could feel safe coding against it more. I could also work toward writing tests for each model.

**Comment by zaneadix** [comment]
@phalt Thanks man :)

**Pull request merged**
