### PR TITLE
Migration cleanup

### LINKED ISSUE #114: Fresh Database build fails with "Conflicting migrations"
Hello again guys-

I noticed the following error when trying to build the database from scratch

```bash
root@pokeapi-dev:~/pokeapi# python manage.py migrate --settings=config.docker
CommandError: Conflicting migrations detected (0001_squashed_0006_pokemonformsprites, 0001_squashed_0002_auto_20151228_0417 in pokemon_v2).
To fix them run 'python manage.py makemigrations --merge'

root@pokeapi-dev:~/pokeapi# python manage.py makemigrations --merge
Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/__init__.py", line 385, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/__init__.py", line 377, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/base.py", line 288, in run_from_argv
    self.execute(*args, **options.__dict__)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/base.py", line 338, in execute
    output = self.handle(*args, **options)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/commands/makemigrations.py", line 85, in handle
    return self.handle_merge(loader, conflicts)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/commands/makemigrations.py", line 186, in handle_merge
    raise ValueError("Could not find common ancestor of %s" % migration_names)
ValueError: Could not find common ancestor of set([u'0001_squashed_0006_pokemonformsprites', u'0001_squashed_0002_auto_20151228_0417'])

```
I walked commits backwards and the last commit that I do not see this issue is @c966153
I'm not sure where to start troubleshooting with this one.. Let me know if you think it's a pretty simple fix I could PR myself.

As always, I just wanted to pass on my thanks for everyone's work on this...
I'm super close to being able to ship something I've been working on for awhile and I wouldn't really be anywhere without this project!

### PR DESCRIPTION
**Pull request by zaneadix**
resolve #114.

@phalt had some diverging migration paths from two separate commits. Accidentally commited both to the repo. Unfortunately I was not able to just wipe one away, make migrations and be done with it. I ended up having to run some commands manually. This may not be the case for others but I'm including them just in case.
```
CREATE TABLE "pokemon_v2_pokemonsprites" ("id" serial NOT NULL PRIMARY KEY, "sprites" varchar(500) NOT NULL, "pokemon_id" integer NULL);
CREATE TABLE "pokemon_v2_itemsprites" ("id" serial NOT NULL PRIMARY KEY, "sprites" varchar(500) NOT NULL, "item_id" integer NULL);
CREATE TABLE "pokemon_v2_pokemonformsprites" ("id" serial NOT NULL PRIMARY KEY, "sprites" varchar(500) NOT NULL, "pokemon_form_id" integer NULL);
CREATE INDEX pokemon_v2_pokemonsprites_acf1160d ON "pokemon_v2_pokemonsprites" ("pokemon_id");
ALTER TABLE "pokemon_v2_pokemonsprites" ADD CONSTRAINT "pokemon_v2_pokemon_id_2c6fc4cc4144650d_fk_pokemon_v2_pokemon_id" FOREIGN KEY ("pokemon_id") REFERENCES "pokemon_v2_pokemon" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX pokemon_v2_itemsprites_82bfda79 ON "pokemon_v2_itemsprites" ("item_id");
ALTER TABLE "pokemon_v2_itemsprites" ADD CONSTRAINT "pokemon_v2_itemsp_item_id_aaf42930681d3ff_fk_pokemon_v2_item_id" FOREIGN KEY ("item_id") REFERENCES "pokemon_v2_item" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX pokemon_v2_pokemonformsprites_277de582 ON "pokemon_v2_pokemonformsprites" ("pokemon_form_id");
ALTER TABLE "pokemon_v2_pokemonformsprites" ADD CONSTRAINT "p_pokemon_form_id_7382ec8a2bfd50c1_fk_pokemon_v2_pokemonform_id" FOREIGN KEY ("pokemon_form_id") REFERENCES "pokemon_v2_pokemonform" ("id") DEFERRABLE INITIALLY DEFERRED;
```
I also ran into some permissions issues but I believe that was just my system. Had to reassign ownership of some sequences. cant remember the commands atm. let me know if you need more info.

### CODE REVIEW

**Comment by zaneadix** [comment]
@OrangeCrush This should fix your issues, Max. Could you try pulling this branch and seeing if you can get it working? you can message me for help if you craps out on you.

**Comment by OrangeCrush** [comment]
Sure!  I will pull this branch down and test the build.

**Comment by OrangeCrush** [comment]
@zaneadix 

I am able to see docker build now complete the database migrations successfully. 
I will wait until I see that the build has completed.. do a little spot checking... and update with my findings here.

 Thanks for your quick and detailed work on this! :+1: 

```
[root@docker:~/pokeapi   BASH]
# docker build -t pokeapi .
...
....
Step 8 : RUN sudo -u postgres service postgresql start                                 &&     sudo -u postgres psql --command "CREATE USER ash WITH PASSWORD 'pokemon'" &&     sudo -u postgres createdb -O ash pokeapi                                  &&     python manage.py migrate --settings=config.docker                         &&     printf "from data.v2.build import build_all; build_all()" | python manage.py shell --settings=config.docker
 ---> Running in 692ef7bf9ff6
 * Starting PostgreSQL 9.3 database server
   ...done.
CREATE ROLE
Operations to perform:
  Synchronize unmigrated apps: rest_framework, corsheaders
  Apply all migrations: hits, sessions, admin, pokemon_v2, sites, auth, tastypie, contenttypes, pokemon
Synchronizing apps without migrations:
  Creating tables...
    Creating table corsheaders_corsmodel
  Installing custom SQL...
  Installing indexes...
Running migrations:
  Applying contenttypes.0001_initial... OK
  Applying auth.0001_initial... OK
  Applying admin.0001_initial... OK
  Applying hits.0001_squashed_0002_resourceview_version... OK
  Applying pokemon.0001_initial... OK
  Applying pokemon_v2.0001_squashed_0002_auto_20160301_1408... OK
  Applying sessions.0001_initial... OK
  Applying sites.0001_initial... OK
  Applying tastypie.0001_initial... OK
Python 2.7.6 (default, Jun 22 2015, 17:58:13) 
[GCC 4.8.2] on linux2
Type "help", "copyright", "credits" or "license" for more information.
(InteractiveConsole)
```

**Comment by OrangeCrush** [comment]
Zane - 
As expected the db build completed fine.  Looks good for a merge to me.  Thanks again!

**Comment by phalt** [comment]
Great team work folks! :+1:

**Pull request merged**
